Rails.application.routes.draw do
  # get 'pages/home'
  # get 'pages/home2'
  # get 'pages/home3'
  # get 'pages/email'
  #
  # get '/thestudio', to: 'pages#thestudio'
  # get '/theconcept', to: 'pages#theconcept'
  # get '/happeningnow', to: 'pages#happeningnow'
  # get '/meetandgreet', to: 'pages#meetandgreet'
  # get '/communityboard', to: 'pages#communityboard'
  # get '/home', to: 'pages#home'
  # get '/rentvenue', to: 'pages#rentvenue'
  # get '/windowshopping', to: 'pages#windowshopping'
  # get '/socialize', to: 'pages#socialize'

  get '/thestudio', to: 'pages#email'
  get '/theconcept', to: 'pages#email'
  get '/happeningnow', to: 'pages#email'
  get '/meetandgreet', to: 'pages#email'
  get '/communityboard', to: 'pages#email'
  get '/home', to: 'pages#email'
  get '/rentvenue', to: 'pages#email'
  get '/windowshopping', to: 'pages#email'
  get '/socialize', to: 'pages#email'
  root 'pages#email'
end
